server:
  port: 80

spring:
  application:
    name: cloud-consumer-service

eureka:
  client:
    #是否从EurekaServer抓取已有的注册信息
    fetch-registry: true
    #是否注册为微服务
    register-with-eureka: true
    service-url:
      #注册到那个注册中心
      defaultZone: http://localhost:7001/eureka
